### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by odeke-em** [opencensus-integrations/ocsql#1]
Thank you for working on this @basvanbeek!

I have a question: is there a plan to add metrics? I ask because I am currently using this package for instrumenting the Google CloudSQL Proxy and it is working great for Tracing, but they also want metrics. If that isn't on the horizon, not a problem, please don't feel pressured

### Sample results
<img width="1453" alt="screen shot 2018-06-19 at 11 32 35 pm" src="https://user-images.githubusercontent.com/4898263/41641139-1e9203c0-7419-11e8-9dc6-3275398cd936.png">

<img width="1458" alt="screen shot 2018-06-19 at 11 32 47 pm" src="https://user-images.githubusercontent.com/4898263/41641146-23f2b224-7419-11e8-93d9-e9fb1c6389d2.png">

**Comment by basvanbeek** [comment]
no it absolutely is in scope... let's discuss what kind of metrics we should emit.

**Comment by odeke-em** [comment]
So currently, for starters I am thinking:
a) Roundtrip latency, with a tag on the method invoked e.g "tag=query"
b) Ping counts, errors
c) General error rates
d) Authentication errors
e) If possible, bytes written and read <-- however this might be tricky as might involve wrapping net.Conn?

This isn't an exhaustive list and I have a meeting with the team on Thursday i.e. in 36 hours, and I'll also bring this up to them too. For now though I can deliver to them metrics from the proxy itself.

**Comment by rafaeljesus** [comment]
+1 for metrics collection, I'd say covering the RED method we are good enough as a first iteration. Any ideia when are you peeps planning to start with it? Thanks

**Comment by derekperkins** [comment]
Now that Go 1.11 is out, we have access to more stats in the stdlib as well.
https://golang.org/pkg/database/sql/#DBStats

**Comment by johanbrandhorst** [comment]
Bump? This would be a really valuable addition. What's the priority of this repo vs other opencensus work?

**Comment by directionless** [comment]
FWIW in my code base, I just started playing with connecting [DBStats](https://golang.org/pkg/database/sql/#DBStats) to opencensus. For us, I think the the top fields are InUse, Idle, WaitCount, and WaitDuration. (and the latter two are possible duplicative)

I'm currently working through hassles relating to how it's all aggregated, and how it connects to stack driver. But having this here would be amazing
