### ISSUE TITLE
Doesn't support non-standard types

### ISSUE THREAD

**Issue by derekperkins** [opencensus-integrations/ocsql#10]
I'm using this successfully with https://github.com/go-sql-driver/mysql, but am having issues with https://github.com/kshvakov/clickhouse. It supports extra data types, including slices, but when using this wrapper, I get the error:
`sql: converting argument $26 type: unsupported type []int16, a slice of int16`

**Comment by basvanbeek** [comment]
@derekperkins, I've verified the issue. Will work on a fix tomorrow, thanks!

**Comment by basvanbeek** [comment]
@derekperkins 

fixed with #13, if still having issues feel free to reopen.

thanks!

**Comment by derekperkins** [comment]
Thanks for the quick turnaround @basvanbeek! That seems to have fixed my issue. The driver I'm working with has some other issues, so I don't know for sure, but it isn't dying in the same spot as before. :)
