### ISSUE TITLE
Implement driver.DriverContext and driver.Connector interfaces

### ISSUE THREAD

**Issue by basvanbeek** [opencensus-integrations/ocsql#11]
To support improved connection pool handling Go 1.10 has added the driver.DriverContext and driver.Connector interfaces. Currently ocsql will hide these interfaces to database/sql so actual databases supporting this will be downgraded to regular Driver interface support if wrapped by ocsql.

**Comment by basvanbeek** [comment]
closed with #13

**Comment by derekperkins** [comment]
Will that be changed at some point or will it always use the old interface? I'm curious why the change and what the ramifications are.

**Comment by basvanbeek** [comment]
I already added these interfaces to ocsql. Only problem we can encounter is that a call to ocsql.Register might fail. If that happens we need to either use the explicit wrapping logic, add a traceoption to feed a working datasourceName to the Register call or have a new function added to database/sql which allows to get driver.Driver from a registered driver name.
