### ISSUE TITLE
Start using versioned releases

### ISSUE THREAD

**Issue by ironsmile** [opencensus-integrations/ocsql#12]
At this moment there are not version tags for this library (e.g. v1.2.3) which forces users to use the master branch. This makes reproducible builds harder than they should be.

Version would be really important very soon with go1.12 once [modules](https://research.swtch.com/vgo) are enabled by default. It makes sense to start now instead of waiting for it to become a problem.

**Comment by basvanbeek** [comment]
Agreed... working on some updates at the moment after which I will tag a first release

**Comment by ironsmile** [comment]
Great! Thank you for this package btw!

**Comment by basvanbeek** [comment]
@ironsmile I just released v0.1.0.
