### ISSUE TITLE
Custom import path

### ISSUE THREAD

**Issue by derekperkins** [opencensus-integrations/ocsql#16]
Having the go import path refer to github instead of the `go.opencensus.io` domain or something else like `contrib.go.opencensus.io/exporter/stackdriver` makes this package feel somewhat less official. Not a huge deal, but probably easier to change sooner rather than later.

**Comment by odeke-em** [comment]
Great suggestion @derekperkins, we've got the Go vanity URLs repo at https://github.com/census-ecosystem/opencensus-go-vanityurls/ Perhaps something like `contrib.go.opencensus.io/integrations/ocsql`?

**Comment by songy23** [comment]
> Perhaps something like contrib.go.opencensus.io/integrations/ocsql?

SGTM

**Comment by songy23** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-website/pull/378.

**Comment by odeke-em** [comment]
Hey @songy23 or @rakyll could you please update the Go vanityURL server?

Currently getting this
```shell
$ go get contrib.go.opencensus.io/integrations/ocsql
package contrib.go.opencensus.io/integrations/ocsql: unrecognized import path "contrib.go.opencensus.io/integrations/ocsql" (parse https://contrib.go.opencensus.io/integrations/ocsql?go-get=1: no go-import meta tags ())
```

In the meantime though am going to reopen this issue since this has been broken for the past 2 days.

**Comment by songy23** [comment]
Unfortunately I don't have permission to run the scripts:
```bash
$ ERROR: (gcloud.app.deploy) Permissions error fetching application [apps/opencensus-go-contrib]. Please make sure you are using the correct project ID and that you have permission to view applications on the project.
```

@rakyll can you help on this?

**Comment by rakyll** [comment]
@songy23 can you please try again?

**Comment by songy23** [comment]
Thanks! Now I'm able to deploy the vanity urls:
```
...
File upload done.
Updating service [default]...done.                                                                         
Updating service [default]...Waiting for operation [apps/opencensus-go-contrib/operations/20607ad2-7923-4259-830a-b41ab9f7c3cd] to compl
ete...done.                                                                                                
Updating service [default]...done.                                                                         
Deployed service [default] to [https://opencensus-go-contrib.appspot.com]
```

`go get contrib.go.opencensus.io/integrations/ocsql` works now. /cc @odeke-em
