### ISSUE TITLE
Doesn't support MemSQL with mysql driver

### ISSUE THREAD

**Issue by bgpat** [opencensus-integrations/ocsql#17]
I've used MemSQL with [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql). I tried to trace with `ocsql`, however below error occurred:

```
Error 1295: MemSQL does not support server-side prepared statements. Many client drivers support client-side prepared statements which work with MemSQL.
```

MemSQL requires client-side prepared statements. In golang, we can use with [`interpolateParams=true`](https://github.com/go-sql-driver/mysql#interpolateparams). With this parameter, the driver doesn't use [`Prepare()` method](https://golang.org/src/database/sql/sql.go#L1367).

[`Queryer`](https://godoc.org/database/sql/driver#Queryer) is not implemented in the wrapped driver, so the driver executes `db.Prepare()`. (https://golang.org/src/database/sql/sql.go#L1561)

**Comment by basvanbeek** [comment]
@bgpat thanks for reporting the issue. I've tested with MemSQL and now it will succeed if using `interpolateParams=true`.

If you still encounter issues feel free to reopen.

**Comment by bgpat** [comment]
It has worked in my environt too. Thanks!
