### ISSUE TITLE
Add function to wrap a driver.Conn directly

### ISSUE THREAD

**Issue by zombiezen** [opencensus-integrations/ocsql#24]
To implement a `driver.Connector`, it would be convenient to wrap `driver.Conn` directly instead of having to wrap it in a driver. Can this functionality be exposed more directly?

**Comment by odeke-em** [comment]
Thank you filing this issue @zombiezen! I'll kindly page @basvanbeek too.

**Comment by zombiezen** [comment]
Much appreciated! I'd be happy to send a PR if there's agreement that this is the right thing to do. I'm adding PostgreSQL support to Go Cloud and this feature would make it significantly simpler to add automatic OpenCensus metrics.

**Comment by basvanbeek** [comment]
I see no issue adding this logic. Will have a solution ready today.

**Comment by zombiezen** [comment]
Thank you @basvanbeek! And if we could get a new tagged release that includes this addition, that would be great. 👍

**Comment by basvanbeek** [comment]
@zombiezen new release v0.1.2 is available

**Comment by zombiezen** [comment]
Thanks Bas!
