### ISSUE TITLE
Support wrapping a driver.Connector instance

### ISSUE THREAD

**Issue by sagikazarmark** [opencensus-integrations/ocsql#30]
As far as I can see, currently one cannot spare the global registration of the ocsql driver.

Wrapping a `driver.Connector` interface (instead of opening one from a `driver.DriverContext` would make that possible.

**Comment by sagikazarmark** [comment]
@basvanbeek what do you think?

**Comment by basvanbeek** [comment]
Yes, that is a relatively minor addition. It would work for database drivers that support setting up a new driver.Connector as available in database/sql from Go 1.10+ (e.q. lib/pq's  `pq.NewConnector`)

I'll add a PR for this shortly.
