### ISSUE TITLE
Not working with sqlx named queries

### ISSUE THREAD

**Issue by rafaeljesus** [opencensus-integrations/ocsql#8]
Hi there,

I am trying to use ocsql with [jmoiron/sqlx](https://github.com/jmoiron/sqlx) apparently everything goes well expect when using sqlx [named queries](https://godoc.org/github.com/jmoiron/sqlx#DB.NamedQueryContext)

Do you have any suggestion how could I make this work?

Here is what I have ATM

```go
driverName, _ := ocsql.Register("postgres", ocsql.WithAllTraceOptions())
sqlDB, _ := sql.Open(driverName, "my.db")

// wraps for a pre-existing *sql.DB.
db := sqlx.NewDb(sqlDB, driverName)

rows, err = db.NamedQueryContext(
  ctx,
  "SELECT .... OFFSET :offset",
  ma[string]interface{}{"offset": 0}
)
```

`pq: syntax error at or near \"OFFSET\"`

Thank you

**Comment by basvanbeek** [comment]
Interesting problem. jmoiron/sqlx named queries need to be converted to the regular bind syntax of the actual database. For this it checks the db driver name. since the driverName from a wrapped ocsql database is unknown to jmoiron/sqlx it fails.

Fortunately it is very easy to fix by doing this:
```go
driverName, _ := ocsql.Register("postgres", ocsql.WithAllTraceOptions())
sqlDB, _ := sql.Open(driverName, "my.db")

// wraps for a pre-existing *sql.DB.
// sqlx asks for the driverName so it knows how to convert certain query constructs 
// for the specified database.
// Let sqlx know we're using Postgresql
db := sqlx.NewDb(sqlDB, "postgres")

rows, err = db.NamedQueryContext(
  ctx,
  "SELECT .... OFFSET :offset",
  map[string]interface{}{"offset": 0},
)
```

**Comment by rafaeljesus** [comment]
@basvanbeek really appreciate your quick reply, I tested here and it worked, thanks a lot
